WEREWOLF = 'Werewolf'
VILLAGER = 'Villager'
MINION = 'Minion'
ROBBER = 'Robber'
TROUBLEMAKER = 'Troublemaker'
SEER = 'Seer'
INSOMNIAC = 'Insomniac'
TANNER = 'Tanner'
MASON = 'Mason'
DOG_WHISPERER = 'Dog Whisperer'
DEVILS_ADVOCATE = 'Devil\'s Advocate'
STONER = 'Stoner'
RATIONALIST = 'Rationalist'
AGENT_OF_CHAOS = 'Agent of Chaos'
INEXPLICABLE = 'Inexplicable'
BOY_NEXTDOOR = 'Boy Nextdoor'
NUT_JOB = 'Nut Job'
PODCASTER = 'Podcaster'

ALL_ROLES = [
    WEREWOLF, VILLAGER, MINION, ROBBER, TROUBLEMAKER, SEER, INSOMNIAC, TANNER, MASON,
    DOG_WHISPERER, DEVILS_ADVOCATE, STONER, RATIONALIST, AGENT_OF_CHAOS, INEXPLICABLE,
    BOY_NEXTDOOR, NUT_JOB, PODCASTER
]

ORDERED_NIGHT_ROLES = [
    WEREWOLF, MINION, DEVILS_ADVOCATE, DOG_WHISPERER, MASON, SEER, AGENT_OF_CHAOS,
    STONER, ROBBER, TROUBLEMAKER, INSOMNIAC, INEXPLICABLE
]
